"""
TripleTen Cloud Platform — Autonomous Incident Defense
======================================================
Module:             packages/contracts/src/tripleten_contracts/__init__.py
Component:          Shared Contract Public Surface
Purpose:            Re-exports the canonical identifiers, state machine, and event contract
                    consumed by
                    incident-agent-api, remediation-worker, and the generated frontend types.
Interacts With:     incident-agent-api (:8000), remediation-worker (internal), incident-war-room (:3000)

Curriculum Project:  Cross-cutting — Modular Ports & Contract Design
Skills:             Contract-First Design, API Surface Design
Tools:              Python 3.11, Pydantic 2
"""

from tripleten_contracts.events import (
    EVENT_CLASS_BY_TYPE,
    EVENT_TYPE_BY_PAYLOAD,
    INCIDENT_EVENT_ADAPTER,
    SSE_EVENT_NAME,
    SSE_RETRY_MS,
    AgentPhase,
    AgentThoughtEvent,
    AgentThoughtPayload,
    BaseIncidentEvent,
    EventPayload,
    EventType,
    GuardrailVerdict,
    IncidentEvent,
    LogStreamEvent,
    LogStreamPayload,
    MalformedFrameError,
    MetricsUpdateEvent,
    RagMatchEvent,
    RagMatchPayload,
    ToolCall,
    UnknownPayloadError,
    WorkerLogEvent,
    WorkerLogLevel,
    WorkerLogPayload,
    WorkerLogSource,
    build_event,
    event_type_for,
    sse_format,
    sse_retry_preamble,
)
from tripleten_contracts.identifiers import (
    APPROVAL_PROMPT,
    READ_ONLY_TOOLS,
    REMEDIATION_TOOLS,
    SCENARIO_TOOLS,
    BucketName,
    QueueName,
    RedisKey,
    RunbookId,
    ScenarioId,
    ToolName,
    postmortem_key,
)
from tripleten_contracts.jobs import CallbackStatus, RemediationJob, WorkerCallback
from tripleten_contracts.security import REDACTION_TOKENS, RedactionType, redaction_token
from tripleten_contracts.states import LEGAL_TRANSITIONS, TERMINAL_STATES, IncidentState
from tripleten_contracts.telemetry import (
    BASELINE_BANDS,
    HEALTH_DEGRADED,
    HEALTH_DOWN,
    HEALTH_OK,
    METRIC_KINDS,
    SCENARIO_SLUG,
    GoldenSignals,
    InfrastructureMetrics,
    MetricKind,
    MetricName,
    MetricsSnapshot,
    Quantile,
    TelemetrySnapshotResponse,
    health_status_for,
)

__all__ = [
    "BASELINE_BANDS",
    "EVENT_CLASS_BY_TYPE",
    "EVENT_TYPE_BY_PAYLOAD",
    "HEALTH_DEGRADED",
    "HEALTH_DOWN",
    "HEALTH_OK",
    "INCIDENT_EVENT_ADAPTER",
    "LEGAL_TRANSITIONS",
    "METRIC_KINDS",
    "SCENARIO_SLUG",
    "SSE_EVENT_NAME",
    "SSE_RETRY_MS",
    "TERMINAL_STATES",
    "AgentPhase",
    "AgentThoughtEvent",
    "AgentThoughtPayload",
    "BaseIncidentEvent",
    "BucketName",
    "EventPayload",
    "EventType",
    "GoldenSignals",
    "GuardrailVerdict",
    "IncidentEvent",
    "IncidentState",
    "InfrastructureMetrics",
    "LogStreamEvent",
    "LogStreamPayload",
    "MalformedFrameError",
    "MetricKind",
    "MetricName",
    "MetricsSnapshot",
    "MetricsUpdateEvent",
    "Quantile",
    "QueueName",
    "APPROVAL_PROMPT",
    "CallbackStatus",
    "READ_ONLY_TOOLS",
    "REDACTION_TOKENS",
    "REMEDIATION_TOOLS",
    "RedactionType",
    "RemediationJob",
    "SCENARIO_TOOLS",
    "WorkerCallback",
    "postmortem_key",
    "redaction_token",
    "RedisKey",
    "RagMatchEvent",
    "RagMatchPayload",
    "RunbookId",
    "ScenarioId",
    "TelemetrySnapshotResponse",
    "ToolCall",
    "ToolName",
    "UnknownPayloadError",
    "WorkerLogEvent",
    "WorkerLogLevel",
    "WorkerLogPayload",
    "WorkerLogSource",
    "build_event",
    "event_type_for",
    "health_status_for",
    "sse_format",
    "sse_retry_preamble",
]
